trigger:
  branches:
    include:
      - main  # or your desired branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

# Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Run your tests with pytest
- script: |
    pytest --alluredir=allure-results --env $(env)
  displayName: 'Run tests with pytest'

# Install Allure CLI
- script: |
    sudo apt-add-repository ppa:qameta/allure
    sudo apt-get update
    sudo apt-get install allure
  displayName: 'Install Allure CLI'

# Generate Allure Report
- script: |
    allure generate allure-results --clean -o allure-report
  displayName: 'Generate Allure Report'

# Publish the report as an artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'allure-report'
    ArtifactName: 'AllureReport'
    publishLocation: 'Container'
  displayName: 'Publish Allure Report'

